Correcting logout url
harshhhdev/harshhhdev.github.io pull request #18
Opened 2022-07-08 10:14 UTC by heykapil

2022-07-08 21:51 UTC, harshhhdev approved these changes

2022-07-08 21:53 UTC, harshhhdev requested changes
Hey Kapil,

Thanks for this correction. I'll merge it in, but I believe the same issue persists on `components/Shortener.tsx`. If you could also fix that, it'd be nice.

2022-07-09 06:09 UTC, heykapil commented
Yes, same logout issue was on url shortner component `components/Shortner.tsx` as well. Just a minor change in next-auth logout url. `/api/auth/signout` instead of `/api/auth/logout`

2022-07-10 02:59 UTC, harshhhdev approved these changes

2022-07-10 02:59 UTC, harshhhdev commented
Looks good. Thank you for this @heykapil.

2022-07-10 02:59 UTC, merged